nvproxy: Remove 535.104.05 from the list of supported drivers.
Installing this driver breaks on Buildkite:
```
ERROR: modpost: GPL-incompatible module nvidia.ko uses GPL-only symbol 'rcu_read_unlock_strict'
```

Might be related to NVIDIA/open-gpu-kernel-modules#594

PiperOrigin-RevId: 633661680