buildkite/Make: Add short delay after reloading Docker, restart bazel.
The Docker reload command (especially when it's just SIGHUP) can race with
future CI instructions that use the bazel container, causing races.

Example CI logs:

```
--- CONFIGURE buildkite_runtime → [...]

2026/07/17 21:29:36 Clobber is set. Overwriting runtime buildkite_runtime not found: adding

2026/07/17 21:29:36 Successfully updated config.

--- DOCKER RELOAD

+ sudo systemctl reload docker

+ docker info --format '{{range $k,$v:=.Runtimes}}{{println $k}}{{end}}'

+ grep -qF buildkite_runtime

--- TEST --test_env=RUNTIME=buildkite_runtime [...] //test/[...]

Error: No such container: gvisor-bazel-1f42b90b-x86_64

Makefile:282: recipe for target 'nodejs22.2.0-runtime-tests' failed

make: *** [nodejs22.2.0-runtime-tests] Error 1
```

Not a great fix, but hopefully this fixes it.

PiperOrigin-RevId: 949850411